### ISSUE TITLE
Use ARG instead of ENV in Dockerfile?

### ISSUE THREAD

**Issue by moderndeveloperllc** [fholzer/docker-nginx-brotli#27]
As a quick workaround to having to update the Dockerfile for every point release of nginx, it might be nice to be able to provide an version at build time from a Compose file (or command line) like:
```
nginx_brotli:
    image: fholzer/nginx-brotli
    container_name: nginx_brotli
    build:
      args:
        NGINX_VERSION: '1.17.5'
```

I believe the Dockerfile could be constructed like:
```
ARG NGINX_VERSION=1.16.1
ARG NGX_BROTLI_COMMIT=e505dce68acc190cc5a1e780a3b0275e39f160ca 
```
and keep the same bracket syntax in the `RUN` command. I can't see where these version numbers are needed inside the images after build.
